#!/bin/bash
ch=0
while [ ch!=4 ]
do 
echo " menu driven program"
echo "1.sort"
echo "2.search"
echo "3.fibonacci series"
echo " 4. exit "
echo " enter the choice "
read ch
case $ch in
1) echo "enter the number of elements"
    read n
  declare -a a
  for((i=0;i<$n;i++))
  do
  read a[$i]
  done
  for((i=0;i<n-1;i++))
  do  
  for((j=i+1;j<n;j++))
    do
      if [ ${a[i]} -gt ${a[j]} ]
      then    
      temp=${a[i]}
      a[i]=${a[j]}
      a[j]=$temp
      fi
      done

  done  

  echo "  ${a[*]}   "

    ;;
2) echo " enter the number of elements "
  read n
  echo " enter the elements "
  for((i=0;i<n;i++))
  do
  read a[$i]
  done
  echo " enter the element to search"
  read key
flag=0
for((i=0;i<n;i++))
do
  if [ ${a[i]} == $key ]
then 
flag=1
echo " the element is found at index $i"
break
fi 
done
if [ $flag == 0 ]
then 
echo " the number $key is not found "
fi 

;;
3)
echo "enter the size"
read n
a1=0;
a2=1;
for((i=0;i<n;i++))
do
echo " $a1 "
a2=$((a1 + a2))
a1=$((a2 - a1))
done 
;;
4)esac "exiting......"
*) echo " invalid choice " 
esac
done
